# Generated by Django 5.1.1 on 2024-10-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
