# Generated by Django 5.1.1 on 2024-10-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('photos', '0002_delete_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
